//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemberAdmin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all).
        /// </summary>
        internal static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All members.
        /// </summary>
        internal static string AllMembers {
            get {
                return ResourceManager.GetString("AllMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomalies.
        /// </summary>
        internal static string Anomaies {
            get {
                return ResourceManager.GetString("Anomaies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachement.
        /// </summary>
        internal static string Attachement {
            get {
                return ResourceManager.GetString("Attachement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC.
        /// </summary>
        internal static string BCC {
            get {
                return ResourceManager.GetString("BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        internal static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string CertificateAccept {
            get {
                return ResourceManager.GetString("CertificateAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and accept; Code:.
        /// </summary>
        internal static string CertificateAcceptInfo {
            get {
                return ResourceManager.GetString("CertificateAcceptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Administration.
        /// </summary>
        internal static string CertificateAdmin {
            get {
                return ResourceManager.GetString("CertificateAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string CertificateFind {
            get {
                return ResourceManager.GetString("CertificateFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate not found..
        /// </summary>
        internal static string CertificateNotFound {
            get {
                return ResourceManager.GetString("CertificateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string CertificateRevoke {
            get {
                return ResourceManager.GetString("CertificateRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create data.
        /// </summary>
        internal static string CommitCreate {
            get {
                return ResourceManager.GetString("CommitCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data.
        /// </summary>
        internal static string CommitDelete {
            get {
                return ResourceManager.GetString("CommitDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operation to commit..
        /// </summary>
        internal static string CommitNoOperation {
            get {
                return ResourceManager.GetString("CommitNoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no update to commit..
        /// </summary>
        internal static string CommitNoUpdate {
            get {
                return ResourceManager.GetString("CommitNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data.
        /// </summary>
        internal static string CommitUpdate {
            get {
                return ResourceManager.GetString("CommitUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notation {0}.
        /// </summary>
        internal static string DateInfo {
            get {
                return ResourceManager.GetString("DateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you really want to to delete this data, please enter the security code..
        /// </summary>
        internal static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a ticket for this error.&lt;br&gt;Bitte erstelle ein Ticket für diesen Fehler..
        /// </summary>
        internal static string ErrorPageAdmin {
            get {
                return ResourceManager.GetString("ErrorPageAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error / Fehler.
        /// </summary>
        internal static string ErrorPageError {
            get {
                return ResourceManager.GetString("ErrorPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error / Unbekannter Fehler.
        /// </summary>
        internal static string ErrorPageUnknownError {
            get {
                return ResourceManager.GetString("ErrorPageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string Fix {
            get {
                return ResourceManager.GetString("Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair (Member).
        /// </summary>
        internal static string FixToMember {
            get {
                return ResourceManager.GetString("FixToMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair (Non-member).
        /// </summary>
        internal static string FixToNonMember {
            get {
                return ResourceManager.GetString("FixToNonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://projects.piratenpartei.ch/knowledgebase/articles/86.
        /// </summary>
        internal static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://projects.piratenpartei.ch/knowledgebase/articles/86#Search.
        /// </summary>
        internal static string HelpUrlSearch {
            get {
                return ResourceManager.GetString("HelpUrlSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a request to join the party. If you approve or reject the request, the person and its section, if any will be notified..
        /// </summary>
        internal static string JoinRequestInfo {
            get {
                return ResourceManager.GetString("JoinRequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining.
        /// </summary>
        internal static string JoinRequestTitle {
            get {
                return ResourceManager.GetString("JoinRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        internal static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Languages.
        /// </summary>
        internal static string LanguagesAll {
            get {
                return ResourceManager.GetString("LanguagesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a request to leave the party. If you approve or reject the request, the person and its section, if any will be notified..
        /// </summary>
        internal static string LeaveRequestInfo {
            get {
                return ResourceManager.GetString("LeaveRequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving.
        /// </summary>
        internal static string LeaveRequestTitle {
            get {
                return ResourceManager.GetString("LeaveRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string ListRequest {
            get {
                return ResourceManager.GetString("ListRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texts.
        /// </summary>
        internal static string ListText {
            get {
                return ResourceManager.GetString("ListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load template.
        /// </summary>
        internal static string LoadTemplate {
            get {
                return ResourceManager.GetString("LoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailer.
        /// </summary>
        internal static string Mailer {
            get {
                return ResourceManager.GetString("Mailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail not ready..
        /// </summary>
        internal static string MailNotReady {
            get {
                return ResourceManager.GetString("MailNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Date per row. Notation {0}.
        /// </summary>
        internal static string MultiDateInfo {
            get {
                return ResourceManager.GetString("MultiDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-member.
        /// </summary>
        internal static string NonMember {
            get {
                return ResourceManager.GetString("NonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        internal static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering.
        /// </summary>
        internal static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string PreferredNotificationMethod {
            get {
                return ResourceManager.GetString("PreferredNotificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare.
        /// </summary>
        internal static string Prepare {
            get {
                return ResourceManager.GetString("Prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaccept.
        /// </summary>
        internal static string Reaccept {
            get {
                return ResourceManager.GetString("Reaccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Delete.
        /// </summary>
        internal static string RealDelete {
            get {
                return ResourceManager.GetString("RealDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string RequestView {
            get {
                return ResourceManager.GetString("RequestView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        internal static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string SaftyCodeDest {
            get {
                return ResourceManager.GetString("SaftyCodeDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        internal static string SaftyCodeSource {
            get {
                return ResourceManager.GetString("SaftyCodeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save template.
        /// </summary>
        internal static string SaveTemplate {
            get {
                return ResourceManager.GetString("SaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string SearchFilter {
            get {
                return ResourceManager.GetString("SearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string SearchOutput {
            get {
                return ResourceManager.GetString("SearchOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All persons.
        /// </summary>
        internal static string SectionAll {
            get {
                return ResourceManager.GetString("SectionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members in no section.
        /// </summary>
        internal static string SectionMembers {
            get {
                return ResourceManager.GetString("SectionMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-members.
        /// </summary>
        internal static string SectionPeople {
            get {
                return ResourceManager.GetString("SectionPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string SentDate {
            get {
                return ResourceManager.GetString("SentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abroad.
        /// </summary>
        internal static string StateAbroad {
            get {
                return ResourceManager.GetString("StateAbroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Cantons.
        /// </summary>
        internal static string StateAll {
            get {
                return ResourceManager.GetString("StateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send test mail to me....
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body of the mail supports textile formatting. It will be rendered in text and HTML format. Supported markup is {0}.
        /// </summary>
        internal static string TextileSupportInfo {
            get {
                return ResourceManager.GetString("TextileSupportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To languages.
        /// </summary>
        internal static string ToLanguages {
            get {
                return ResourceManager.GetString("ToLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To notifications.
        /// </summary>
        internal static string ToNotificationMethods {
            get {
                return ResourceManager.GetString("ToNotificationMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To sections.
        /// </summary>
        internal static string ToSections {
            get {
                return ResourceManager.GetString("ToSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Cantons.
        /// </summary>
        internal static string ToStates {
            get {
                return ResourceManager.GetString("ToStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a transfer to another section. If you approve or reject the request, the person and its former and new section, if any will be notified..
        /// </summary>
        internal static string TransferRequestInfo {
            get {
                return ResourceManager.GetString("TransferRequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section transfer.
        /// </summary>
        internal static string TransferRequestTitle {
            get {
                return ResourceManager.GetString("TransferRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown person..
        /// </summary>
        internal static string UnknownPerson {
            get {
                return ResourceManager.GetString("UnknownPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested action is not kown..
        /// </summary>
        internal static string ViewActionError {
            get {
                return ResourceManager.GetString("ViewActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
