//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistrationService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email could not be verified. Please repeat the process..
        /// </summary>
        internal static string CrateAccountEmailVerificationFailed {
            get {
                return ResourceManager.GetString("CrateAccountEmailVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create forum account.
        /// </summary>
        internal static string CreateAccountForum {
            get {
                return ResourceManager.GetString("CreateAccountForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can register for the forum here..
        /// </summary>
        internal static string CreateAccountForumHint {
            get {
                return ResourceManager.GetString("CreateAccountForumHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address is now verified. Please enter your nickname and password..
        /// </summary>
        internal static string CreateAccountInfo {
            get {
                return ResourceManager.GetString("CreateAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for party membership.
        /// </summary>
        internal static string CreateAccountMember {
            get {
                return ResourceManager.GetString("CreateAccountMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can become a member here..
        /// </summary>
        internal static string CreateAccountMemberHint {
            get {
                return ResourceManager.GetString("CreateAccountMemberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match. Please retype them..
        /// </summary>
        internal static string CreateAccountPasswordMismatch {
            get {
                return ResourceManager.GetString("CreateAccountPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password is too short. Please choose another..
        /// </summary>
        internal static string CreateAccountPasswordTooShort {
            get {
                return ResourceManager.GetString("CreateAccountPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        internal static string CreateAccountStep {
            get {
                return ResourceManager.GetString("CreateAccountStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This nickname is already taken. Please choose another..
        /// </summary>
        internal static string CreateAccountUsernameTaken {
            get {
                return ResourceManager.GetString("CreateAccountUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a ticket for this error.&lt;br&gt;Bitte erstelle ein Ticket für diesen Fehler..
        /// </summary>
        internal static string ErrorPageAdmin {
            get {
                return ResourceManager.GetString("ErrorPageAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error / Fehler.
        /// </summary>
        internal static string ErrorPageError {
            get {
                return ResourceManager.GetString("ErrorPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error / Unbekannter Fehler.
        /// </summary>
        internal static string ErrorPageUnknownError {
            get {
                return ResourceManager.GetString("ErrorPageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you may register, your email address needs to be verified..
        /// </summary>
        internal static string InfoVerifyEmail {
            get {
                return ResourceManager.GetString("InfoVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memberservice.
        /// </summary>
        internal static string MemberService {
            get {
                return ResourceManager.GetString("MemberService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your address, phone number, etc. or request a section change or leave here..
        /// </summary>
        internal static string MemberServiceHint {
            get {
                return ResourceManager.GetString("MemberServiceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        internal static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        internal static string PasswordResetDone {
            get {
                return ResourceManager.GetString("PasswordResetDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password? Reset here..
        /// </summary>
        internal static string PasswordResetHint {
            get {
                return ResourceManager.GetString("PasswordResetHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email was sent to the email address of this account. Please check your inbox..
        /// </summary>
        internal static string PasswordResetInfo {
            get {
                return ResourceManager.GetString("PasswordResetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        internal static string PasswordResetNoMatch {
            get {
                return ResourceManager.GetString("PasswordResetNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such password reset information found..
        /// </summary>
        internal static string PasswordResetNoReset {
            get {
                return ResourceManager.GetString("PasswordResetNoReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account with that username or email address found..
        /// </summary>
        internal static string PasswordResetNotFound {
            get {
                return ResourceManager.GetString("PasswordResetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have at least 8 characters..
        /// </summary>
        internal static string PasswordResetTooShort {
            get {
                return ResourceManager.GetString("PasswordResetTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type your new password and repeat to confirm..
        /// </summary>
        internal static string PasswordResetType {
            get {
                return ResourceManager.GetString("PasswordResetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email address:.
        /// </summary>
        internal static string PasswordResetUserOrEmail {
            get {
                return ResourceManager.GetString("PasswordResetUserOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        internal static string RequestMembershipComms {
            get {
                return ResourceManager.GetString("RequestMembershipComms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership options.
        /// </summary>
        internal static string RequestMembershipOptions {
            get {
                return ResourceManager.GetString("RequestMembershipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string RequestMembershipPersonal {
            get {
                return ResourceManager.GetString("RequestMembershipPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RequestMembershipSettings {
            get {
                return ResourceManager.GetString("RequestMembershipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in Switzerland.
        /// </summary>
        internal static string StateAbroad {
            get {
                return ResourceManager.GetString("StateAbroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data..
        /// </summary>
        internal static string ValidateInvalid {
            get {
                return ResourceManager.GetString("ValidateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date. Format {0}.
        /// </summary>
        internal static string ValidateInvalidDate {
            get {
                return ResourceManager.GetString("ValidateInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be empty..
        /// </summary>
        internal static string ValidateNotEmpty {
            get {
                return ResourceManager.GetString("ValidateNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mail has been sent to your email address. Please check your inbox..
        /// </summary>
        internal static string VerfyEmailSent {
            get {
                return ResourceManager.GetString("VerfyEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is not valid. Please check the spelling..
        /// </summary>
        internal static string VerifyEmailInvalid {
            get {
                return ResourceManager.GetString("VerifyEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address verification is outdated. Please verify again..
        /// </summary>
        internal static string VerifyEmailOutdated {
            get {
                return ResourceManager.GetString("VerifyEmailOutdated", resourceCulture);
            }
        }
    }
}
