//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemberService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All members.
        /// </summary>
        internal static string AllMembers {
            get {
                return ResourceManager.GetString("AllMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thise email addresses are only use if the others don&apos;t work..
        /// </summary>
        internal static string AlternateEmailInfo {
            get {
                return ResourceManager.GetString("AlternateEmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To activate your certificate, call the registrar and tell the code below..
        /// </summary>
        internal static string CertificateAuthorization {
            get {
                return ResourceManager.GetString("CertificateAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        internal static string CertificateCode {
            get {
                return ResourceManager.GetString("CertificateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate is created and will now be installed..
        /// </summary>
        internal static string CertificateCreated {
            get {
                return ResourceManager.GetString("CertificateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CertificateDelete {
            get {
                return ResourceManager.GetString("CertificateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install client certificate.
        /// </summary>
        internal static string CertificateDownload {
            get {
                return ResourceManager.GetString("CertificateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string CertificateEdit {
            get {
                return ResourceManager.GetString("CertificateEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string CertificateGrade {
            get {
                return ResourceManager.GetString("CertificateGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select High or at least 2048.
        /// </summary>
        internal static string CertificateGradeInfo {
            get {
                return ResourceManager.GetString("CertificateGradeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string CertificateKey {
            get {
                return ResourceManager.GetString("CertificateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key generation does not work with Internet Explorer. Please use Firefox, Chrome or Opera..
        /// </summary>
        internal static string CertificateNotIE {
            get {
                return ResourceManager.GetString("CertificateNotIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        internal static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your key is too short. Please select High oder at least 2048..
        /// </summary>
        internal static string CertificateTooLow {
            get {
                return ResourceManager.GetString("CertificateTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change address.
        /// </summary>
        internal static string ChangeAddress {
            get {
                return ResourceManager.GetString("ChangeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        internal static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change phone.
        /// </summary>
        internal static string ChangePhone {
            get {
                return ResourceManager.GetString("ChangePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change section.
        /// </summary>
        internal static string ChangeSection {
            get {
                return ResourceManager.GetString("ChangeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you join a section you will automatically become a member of all superordinate sections and you will remain a member of the Pirate Party Switzerland..
        /// </summary>
        internal static string ChangeSectionInfo1 {
            get {
                return ResourceManager.GetString("ChangeSectionInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change of section will be processed by the Registrar. You will be notified once its complete..
        /// </summary>
        internal static string ChangeSectionInfo2 {
            get {
                return ResourceManager.GetString("ChangeSectionInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for party membership.
        /// </summary>
        internal static string CreateAccountMember {
            get {
                return ResourceManager.GetString("CreateAccountMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        internal static string CreateAccountStep {
            get {
                return ResourceManager.GetString("CreateAccountStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create certificates.
        /// </summary>
        internal static string CreateCertificate {
            get {
                return ResourceManager.GetString("CreateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete personal data.
        /// </summary>
        internal static string DeletePersonalData {
            get {
                return ResourceManager.GetString("DeletePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This deletes your personal data including your postal address and phone number, but leaves your forum account and email address..
        /// </summary>
        internal static string DeletePersonalDataInfo {
            get {
                return ResourceManager.GetString("DeletePersonalDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete forum user.
        /// </summary>
        internal static string DeleteUserAccount {
            get {
                return ResourceManager.GetString("DeleteUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This delete your forum account and all personal data..
        /// </summary>
        internal static string DeleteUserAccountInfo {
            get {
                return ResourceManager.GetString("DeleteUserAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download certificate of the authority for the administration.
        /// </summary>
        internal static string DownloadAuthority {
            get {
                return ResourceManager.GetString("DownloadAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address change unknown or outdated..
        /// </summary>
        internal static string EmailAddressChangeUnknown {
            get {
                return ResourceManager.GetString("EmailAddressChangeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These email addresses are used by the Pirate Party to send you information. If you change this, you will get an email to confirm the new address..
        /// </summary>
        internal static string EmailInfo {
            get {
                return ResourceManager.GetString("EmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may define multiple active and multiple alternate email addresses..
        /// </summary>
        internal static string EmailInfo2 {
            get {
                return ResourceManager.GetString("EmailInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid..
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons, pllease enter your password..
        /// </summary>
        internal static string EmailRequiresPassword {
            get {
                return ResourceManager.GetString("EmailRequiresPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a ticket for this error.&lt;br&gt;Bitte erstelle ein Ticket für diesen Fehler..
        /// </summary>
        internal static string ErrorPageAdmin {
            get {
                return ResourceManager.GetString("ErrorPageAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error / Fehler.
        /// </summary>
        internal static string ErrorPageError {
            get {
                return ResourceManager.GetString("ErrorPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error / Unbekannter Fehler.
        /// </summary>
        internal static string ErrorPageUnknownError {
            get {
                return ResourceManager.GetString("ErrorPageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the party.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave account intact.
        /// </summary>
        internal static string LeaveAccount {
            get {
                return ResourceManager.GetString("LeaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to leave are processed by the Registrar. You will be notified when your request was processed..
        /// </summary>
        internal static string LeaveInfo {
            get {
                return ResourceManager.GetString("LeaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason (optional).
        /// </summary>
        internal static string LeaveReason {
            get {
                return ResourceManager.GetString("LeaveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location must not be empty..
        /// </summary>
        internal static string LocationNotEmpty {
            get {
                return ResourceManager.GetString("LocationNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member number.
        /// </summary>
        internal static string MemberNumber {
            get {
                return ResourceManager.GetString("MemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string MembershipStatus {
            get {
                return ResourceManager.GetString("MembershipStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one email address..
        /// </summary>
        internal static string MustHaveEmail {
            get {
                return ResourceManager.GetString("MustHaveEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-member.
        /// </summary>
        internal static string NonMember {
            get {
                return ResourceManager.GetString("NonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        internal static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoVotingRight {
            get {
                return ResourceManager.GetString("NoVotingRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 8 characters long..
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too short..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is wrong..
        /// </summary>
        internal static string PasswordWrong {
            get {
                return ResourceManager.GetString("PasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is not valid..
        /// </summary>
        internal static string PhoneInvalid {
            get {
                return ResourceManager.GetString("PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All persons.
        /// </summary>
        internal static string SectionAll {
            get {
                return ResourceManager.GetString("SectionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members in no section.
        /// </summary>
        internal static string SectionMembers {
            get {
                return ResourceManager.GetString("SectionMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-members.
        /// </summary>
        internal static string SectionPeople {
            get {
                return ResourceManager.GetString("SectionPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
