//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.Ldap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LdapResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LdapResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.Ldap.LdapResources", typeof(LdapResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate mail.
        /// </summary>
        public static string AlternateMail {
            get {
                return ResourceManager.GetString("AlternateMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachement.
        /// </summary>
        public static string Attachement {
            get {
                return ResourceManager.GetString("Attachement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC.
        /// </summary>
        public static string BCC {
            get {
                return ResourceManager.GetString("BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CertificateComment {
            get {
                return ResourceManager.GetString("CertificateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        public static string CertificateFingerprint {
            get {
                return ResourceManager.GetString("CertificateFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string CertificateLevel {
            get {
                return ResourceManager.GetString("CertificateLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CertificateLevel0 {
            get {
                return ResourceManager.GetString("CertificateLevel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CertificateLevel1 {
            get {
                return ResourceManager.GetString("CertificateLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Admin.
        /// </summary>
        public static string CertificateLevel2 {
            get {
                return ResourceManager.GetString("CertificateLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Superadmin.
        /// </summary>
        public static string CertificateLevel3 {
            get {
                return ResourceManager.GetString("CertificateLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, BCNF.
        /// </summary>
        public static string CertificateLevel4 {
            get {
                return ResourceManager.GetString("CertificateLevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        public static string CertificateValidFrom {
            get {
                return ResourceManager.GetString("CertificateValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        public static string CertificateValidUntil {
            get {
                return ResourceManager.GetString("CertificateValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CommonName {
            get {
                return ResourceManager.GetString("CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ContributeClassNormal {
            get {
                return ResourceManager.GetString("ContributeClassNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced.
        /// </summary>
        public static string ContributeClassReduced {
            get {
                return ResourceManager.GetString("ContributeClassReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ContributeClassUnknown {
            get {
                return ResourceManager.GetString("ContributeClassUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string ContributionClass {
            get {
                return ResourceManager.GetString("ContributionClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DN.
        /// </summary>
        public static string DN {
            get {
                return ResourceManager.GetString("DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DomainComponent {
            get {
                return ResourceManager.GetString("DomainComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DomainComponent1 {
            get {
                return ResourceManager.GetString("DomainComponent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member number.
        /// </summary>
        public static string EmployeeNumber {
            get {
                return ResourceManager.GetString("EmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member type.
        /// </summary>
        public static string EmployeeType {
            get {
                return ResourceManager.GetString("EmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member organization.
        /// </summary>
        public static string EmployeeTypeFleet {
            get {
                return ResourceManager.GetString("EmployeeTypeFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-member.
        /// </summary>
        public static string EmployeeTypeLandLubber {
            get {
                return ResourceManager.GetString("EmployeeTypeLandLubber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate.
        /// </summary>
        public static string EmployeeTypePirate {
            get {
                return ResourceManager.GetString("EmployeeTypePirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sympathizer.
        /// </summary>
        public static string EmployeeTypeSympathizer {
            get {
                return ResourceManager.GetString("EmployeeTypeSympathizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Status.
        /// </summary>
        public static string EmployeeTypeUnknown {
            get {
                return ResourceManager.GetString("EmployeeTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharged member.
        /// </summary>
        public static string EmployeeTypeVeteran {
            get {
                return ResourceManager.GetString("EmployeeTypeVeteran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned member.
        /// </summary>
        public static string EmployeeTypeWalkedThePlank {
            get {
                return ResourceManager.GetString("EmployeeTypeWalkedThePlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femaile.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        public static string GenderNotApplication {
            get {
                return ResourceManager.GetString("GenderNotApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string GenderUnknown {
            get {
                return ResourceManager.GetString("GenderUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Givennamen.
        /// </summary>
        public static string Givenname {
            get {
                return ResourceManager.GetString("Givenname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italien.
        /// </summary>
        public static string Italien {
            get {
                return ResourceManager.GetString("Italien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining.
        /// </summary>
        public static string Joining {
            get {
                return ResourceManager.GetString("Joining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        public static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Languages.
        /// </summary>
        public static string LanguagesAll {
            get {
                return ResourceManager.GetString("LanguagesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspeicifed.
        /// </summary>
        public static string LanguageUnspecified {
            get {
                return ResourceManager.GetString("LanguageUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Newsletter.
        /// </summary>
        public static string LastNewsLetter {
            get {
                return ResourceManager.GetString("LastNewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving.
        /// </summary>
        public static string Leaving {
            get {
                return ResourceManager.GetString("Leaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicGlobal.Mailer.
        /// </summary>
        public static string Mailer {
            get {
                return ResourceManager.GetString("Mailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail not ready..
        /// </summary>
        public static string MailNotReady {
            get {
                return ResourceManager.GetString("MailNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In .
        /// </summary>
        public static string NewsletterInLanguage {
            get {
                return ResourceManager.GetString("NewsletterInLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahoi .
        /// </summary>
        public static string NewsletterSalutation {
            get {
                return ResourceManager.GetString("NewsletterSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string NewsletterSelect {
            get {
                return ResourceManager.GetString("NewsletterSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot Voting.
        /// </summary>
        public static string NewsletterSelectBallotVoting {
            get {
                return ResourceManager.GetString("NewsletterSelectBallotVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electoral Campaign.
        /// </summary>
        public static string NewsletterSelectCampaignAction {
            get {
                return ResourceManager.GetString("NewsletterSelectCampaignAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultural Policy.
        /// </summary>
        public static string NewsletterSelectCulturalPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectCulturalPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Policy.
        /// </summary>
        public static string NewsletterSelectDigitalPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectDigitalPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy Policy.
        /// </summary>
        public static string NewsletterSelectEconomyPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectEconomyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Policy.
        /// </summary>
        public static string NewsletterSelectEducationalPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectEducationalPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Policy.
        /// </summary>
        public static string NewsletterSelectEnergyPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectEnergyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Policy.
        /// </summary>
        public static string NewsletterSelectEnvironmentPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectEnvironmentPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Policy.
        /// </summary>
        public static string NewsletterSelectForeignPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectForeignPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Policy.
        /// </summary>
        public static string NewsletterSelectHealthPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectHealthPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string NewsletterSelectInvalid {
            get {
                return ResourceManager.GetString("NewsletterSelectInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Offers.
        /// </summary>
        public static string NewsletterSelectJobOffers {
            get {
                return ResourceManager.GetString("NewsletterSelectJobOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate Assembly.
        /// </summary>
        public static string NewsletterSelectPirateAssembly {
            get {
                return ResourceManager.GetString("NewsletterSelectPirateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Vote Campaign.
        /// </summary>
        public static string NewsletterSelectPopularVoteAction {
            get {
                return ResourceManager.GetString("NewsletterSelectPopularVoteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string NewsletterSelectReports {
            get {
                return ResourceManager.GetString("NewsletterSelectReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Foundings.
        /// </summary>
        public static string NewsletterSelectSectionFounding {
            get {
                return ResourceManager.GetString("NewsletterSelectSectionFounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Policy.
        /// </summary>
        public static string NewsletterSelectSecurityPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectSecurityPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Policy.
        /// </summary>
        public static string NewsletterSelectSocialPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectSocialPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Policy.
        /// </summary>
        public static string NewsletterSelectStatePolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectStatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Policy.
        /// </summary>
        public static string NewsletterSelectTransportPolicy {
            get {
                return ResourceManager.GetString("NewsletterSelectTransportPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@piratenpartei.ch.
        /// </summary>
        public static string NewsletterSenderEmail {
            get {
                return ResourceManager.GetString("NewsletterSenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate Party Switzerland.
        /// </summary>
        public static string NewsletterSenderName {
            get {
                return ResourceManager.GetString("NewsletterSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate greetings.
        /// </summary>
        public static string NewsletterSignature {
            get {
                return ResourceManager.GetString("NewsletterSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter {0}-{1}.
        /// </summary>
        public static string NewsletterSubject {
            get {
                return ResourceManager.GetString("NewsletterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-member.
        /// </summary>
        public static string NonMember {
            get {
                return ResourceManager.GetString("NonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        public static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectClass.
        /// </summary>
        public static string ObjectClass {
            get {
                return ResourceManager.GetString("ObjectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incumbent.
        /// </summary>
        public static string Occupant {
            get {
                return ResourceManager.GetString("Occupant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering.
        /// </summary>
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Group Id.
        /// </summary>
        public static string PiVoteGroupId {
            get {
                return ResourceManager.GetString("PiVoteGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string PreferredNotificationMethod {
            get {
                return ResourceManager.GetString("PreferredNotificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PreferrredNotificationMethodEmail {
            get {
                return ResourceManager.GetString("PreferrredNotificationMethodEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string PreferrredNotificationMethodLetter {
            get {
                return ResourceManager.GetString("PreferrredNotificationMethodLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string PreferrredNotificationMethodUnknown {
            get {
                return ResourceManager.GetString("PreferrredNotificationMethodUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare.
        /// </summary>
        public static string Prepare {
            get {
                return ResourceManager.GetString("Prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaccept.
        /// </summary>
        public static string Reaccept {
            get {
                return ResourceManager.GetString("Reaccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        public static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string SaftyCodeDest {
            get {
                return ResourceManager.GetString("SaftyCodeDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        public static string SaftyCodeSource {
            get {
                return ResourceManager.GetString("SaftyCodeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All persons.
        /// </summary>
        public static string SectionAll {
            get {
                return ResourceManager.GetString("SectionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members in no section.
        /// </summary>
        public static string SectionMembers {
            get {
                return ResourceManager.GetString("SectionMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-members.
        /// </summary>
        public static string SectionPeople {
            get {
                return ResourceManager.GetString("SectionPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string SentDate {
            get {
                return ResourceManager.GetString("SentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canton.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abroad.
        /// </summary>
        public static string StateAbroad {
            get {
                return ResourceManager.GetString("StateAbroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Cantons.
        /// </summary>
        public static string StateAll {
            get {
                return ResourceManager.GetString("StateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send test mail to me....
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UidNumber.
        /// </summary>
        public static string UidNumber {
            get {
                return ResourceManager.GetString("UidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string UniqueIdentifier {
            get {
                return ResourceManager.GetString("UniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown person..
        /// </summary>
        public static string UnknownPerson {
            get {
                return ResourceManager.GetString("UnknownPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting right until.
        /// </summary>
        public static string VotingRightUntil {
            get {
                return ResourceManager.GetString("VotingRightUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
